/** Default form values for DOOH brief generator (matches `dooh_briefs.payload` shape). */

/** Maximum storyboard scenes in the generator (templates include defaults up to this index). */
export const DOOH_BRIEF_SCENE_SLOT_MAX = 12

export const DOOH_BRIEF_GENERATOR_DEFAULTS = {
  slug: 'generated-dooh-brief',
  /** Brief uses this many scenes (1–{@link DOOH_BRIEF_SCENE_SLOT_MAX}); extras slots stay in the form for reuse when adding scenes. */
  scene_count: 1,
  listTitle: 'Brand · Location line',
  listBadge: 'DOOH',
  bannerLabel: 'Brand · DOOH · Street · City · 10s',
  headerPill: 'Live production brief',
  tags: 'DOOH, 10s · Loop-ready, City · Country',
  title: 'HEADLINE TAGLINE',
  subtitle: 'Brand — Full DOOH production brief',
  introHtml:
    'A cinematic build from <b>controlled presence → ignition → motion → brand clarity</b>. Describe the story in one paragraph.',
  creativeArc: 'Attraction, Tension, Trigger, Release, Resolution',

  format_type: 'DOOH · Digital Out-of-Home',
  format_duration: '10.0 seconds · loop-friendly',
  format_attention: 'Must capture within first 1–2 seconds',
  format_readability: 'Peripheral vision - no fine print',
  format_location: 'Main boulevard · City',
  format_loop: 'Last scene fades into reflection of first scene',
  format_vertical: 'casino',

  char_gender: 'female',
  char_type:
    'Confident rider - athletic build (28–30 years old) high-end commercial model appearance',
  char_traits: 'Confident · calm · in control · stylish',
  char_wardrobe: 'Fitted matte-black full-body suit. Clean silhouette, no logos.',
  char_feet: 'Glossy red high-heeled stilettos - the single warm accent element. Visual echo of brand red.',
  char_feet_hot: true,
  char_accessory: 'Helmet held in hand, relaxed and low',
  char_movement: 'Even steps · no exaggeration · natural posture',
  char_postHelmet: 'No facial expression · energy shifts to body mechanics',

  ref1_label: 'Character ref · Full body',
  ref1_file: 'scene1.png',
  ref2_label: 'Character ref · Close-up',
  ref2_file: 'scene2.png',
  ref3_label: 'Character ref · Alt angle',
  ref3_file: 'ref.png',

  camera_cinematic:
    'Soft cinematic side-key, subtle rim. Smooth gimbal, controlled motion. No handheld shake unless specified.',
  camera_billboard:
    'Locked-off or minimal micro-movement for outro. High readability, dominant logo, rotating promo line acceptable.',

  outro_logo_file: 'banner.png',
  outro_logo_badge: 'Actual DOOH design ref',
  outro_comp_center: 'Logo - dominant, large, soft glow halo',
  outro_comp_top: 'Rotating: PROMO LINE A · PROMO LINE B · PLAY RESPONSIBLY',
  outro_comp_bottom: 'TAGLINE - fixed · bold · high readability',
  outro_comp_bg: 'Deep black / charcoal · residual centered glow',
  outro_palette: 'Palette: black dominant · accent center only · white for type',

  footerLine: 'BRAND · TAGLINE · DOOH · 10s · Brief',
  footerMeta: 'Location · Year',

  s1_code: 'S1',
  s1_num: '01',
  s1_title: 'Walk-in · Controlled presence',
  s1_time: '0.0 – 1.2s',
  s1_lens: '35mm',
  s1_hot: false,
  s1_intentHtml:
    '<b>Rear tracking · full body · low angle.</b> Immediate visual hook with controlled presence.',
  s1_promptVideo: `Cinematic realistic video of a confident brunette woman (28–30 years old), slim athletic physique, highly realistic face, walking with purpose on a wet Queen Elisabeth Boulevard in Bucharest, early morning after rain. The boulevard is completely empty, no cars, no pedestrians, surrounded by classical and modern buildings. She wears a tight matte black full-body outfit and glossy red high-heeled stilettos, carrying a matte black motorcycle helmet with the visor open in her right hand. Ahead of her on the wet asphalt is a sleek modern black Yamaha R1 sport motorcycle. The ground is wet with strong reflections of red and amber traffic lights and subtle neon accents, minimal cyberpunk atmosphere, no light trails, no long-exposure look. Lighting is cinematic, high-contrast automotive commercial style, 35mm lens look, shallow depth of field, deep shadows, soft highlights on skin, outfit, and motorcycle. The sky shows a dramatic gradient from deep red/orange near the horizon to cool blue above, moody after-rain atmosphere with enhanced reflections. Camera is a low worm-eye angle, full wide lateral tracking shot moving smoothly from left to right, continuously following her, no cuts, no angle changes, no front view. She walks steadily and confidently, heels subtly contacting the wet surface, approaches the motorcycle, slows down, stops beside it, then smoothly mounts it by swinging her leg over in a controlled motion while keeping the helmet in her hand at all times. Once seated, she stabilizes her posture, briefly pauses, then lifts the helmet with both hands and puts it on her head naturally, adjusting it slightly while keeping the visor open. Her expression remains calm, focused, and self-assured. The motorcycle remains off or idle. Wet asphalt reflections clearly visible, subtle red glow on the ground, motorcycle highly detailed with carbon fiber and metallic highlights, background softly blurred but recognizable. Negative constraints: no cars, no traffic, no pedestrians, no crowd, no light trails, no long exposure, no cuts, no camera changes, no front angle, no distortion, no extra limbs, no blur artifacts, no flickering, no duplicate objects.`,
  s1_promptStill: `full wide lateral-view photograph of a confident young age brunette woman (realistic face) @img2 looking direct on the motorcycle spot @img3 , around 28-30 years old, with a slim, athletic physique , walking toward a sleek modern black sport motorcycle modern r1 in "Queen Elisabeth Boulevard with no cars, reference @img3 , Bucharest, in the morning. She is wearing a full body kit , ultra-sexy dark black matte, to accentuate her curves. She is walking in glossy high-heeled red stilettos on glistening wet asphalt that reflects the red and amber glow of city traffic lights and neon signs and on the wet road beneath the bike, red cyberpunk, emphasizing the after-the-rain atmosphere, strong wet reflections, and subtle minimal cyberpunk-style light accents. In her right hand, she carries a matte black motorcycle helmet by her side , with her arm slightly bent to suggest motion and confidence. The low worm-eye angle emphasizes her powerful, purposeful stride and the sensual lines of her legs, drawing the viewer's eye along the wet reflections toward the motorcycle. The motorcycle is in razor-sharp focus as the destination in the center-right of the frame, its polished metal and carbon fiber surfaces catching subtle highlights. classical and modern buildings Queen Elisabeth Boulevard @img2 ,around the square, a warm sunset gradient transitioning from deep red/red - blue (amurg/early morning) near the horizon to twilight sky above with reflection on the road. Premium high-contrast automotive commercial style, 35mm lens, shallow depth of field, cinematic lighting with deep shadows, soft specular highlights on skin and fabric textures, and a moody, dramatic atmosphere, subtle colored light from red traffic lights and building signs visible on the wet road like a minimal cyberpunk glow red subtle, do not put Car light trails in the image ,the image is not captured using long-exposure photography, don't add cars , after the rain ambiance, enhanced wet road reflections beneath the bike and along the boulevard.
enhanced with realism.`,
  s1_negVideo: 'no smile · no neon · no cyberpunk · no shaky cam',
  s1_negStill: 'no smile · no heavy retouching',
  s1_imageMode: 'file',
  s1_imageFile: 'scene1.png',
  s1_phLabel: '',
  s1_phHint: '',
  s1_badge: 'Reference still',
  s1_brandOutro: false,

  s2_code: 'S2',
  s2_num: '02',
  s2_title: 'Close-up · Calm before ignition',
  s2_time: '1.2 – 2.2s',
  s2_lens: '85mm',
  s2_hot: false,
  s2_intentHtml: '<b>Chest-up · 3/4 · subtle push-in.</b> Pause before action.',
  s2_promptVideo: 'Cinematic chest-up close-up, 85mm. Calm focused expression.',
  s2_promptStill: 'Cinematic close-up still, 85mm, shallow DOF.',
  s2_negVideo: 'no smile · no exaggerated emotion',
  s2_negStill: 'no heavy retouching',
  s2_imageMode: 'file',
  s2_imageFile: 'scene2.png',
  s2_phLabel: '',
  s2_phHint: '',
  s2_badge: 'Reference still · Close-up',
  s2_brandOutro: false,

  s3_code: 'S3',
  s3_num: '03',
  s3_title: 'Rapid ignition · Game on',
  s3_time: '2.2 – 3.8s',
  s3_lens: '35 / 50 / 85mm',
  s3_hot: true,
  s3_intentHtml: '<b>Ultra-fast micro-montage.</b> The "game on" trigger.',
  s3_promptVideo: 'Sequence of tight shots: helmet, visor, throttle, engine.',
  s3_promptStill: 'Close-up still, visor and hands, macro detail.',
  s3_negVideo: 'no random cuts · no shaky cam',
  s3_negStill: 'no fantasy lighting',
  s3_imageMode: 'placeholder',
  s3_imageFile: '',
  s3_phLabel: 'Rapid ignition',
  s3_phHint: 'Add reference still',
  s3_badge: 'Reference pending',
  s3_brandOutro: false,

  s4_code: 'S4',
  s4_num: '04',
  s4_title: 'Power takeoff',
  s4_time: '3.8 – 5.8s',
  s4_lens: '28–35mm',
  s4_hot: false,
  s4_intentHtml: '<b>Low-angle tracking · camera accelerates with subject.</b>',
  s4_promptVideo: 'Cinematic low-angle tracking. Launch and speed.',
  s4_promptStill: 'Cinematic still, low angle, wet road reflections.',
  s4_negVideo: 'no chaotic motion',
  s4_negStill: 'no cartoon effects',
  s4_imageMode: 'file',
  s4_imageFile: 'ref2.png',
  s4_phLabel: '',
  s4_phHint: '',
  s4_badge: 'Environment ref',
  s4_brandOutro: false,

  s5_code: 'S5',
  s5_num: '05',
  s5_title: 'Reward trail · System activation',
  s5_time: '5.8 – 7.8s',
  s5_lens: '35mm + 85mm',
  s5_hot: false,
  s5_intentHtml: '<b>Side-tracking · motion field · rewards attached to motion.</b>',
  s5_promptVideo: 'Stable side-tracking, motion blur city, energy trail.',
  s5_promptStill: 'Still with motion blur and UI cards along motion vector.',
  s5_negVideo: 'no random floating UI',
  s5_negStill: 'no cartoon trails',
  s5_imageMode: 'placeholder',
  s5_imageFile: '',
  s5_phLabel: 'Reward trail',
  s5_phHint: 'Generate side tracking ref',
  s5_badge: 'Visual pending',
  s5_brandOutro: false,

  s6_code: 'S6',
  s6_num: '06',
  s6_title: 'Collapses into identity',
  s6_time: '7.8 – 8.8s',
  s6_lens: '35mm → push-in',
  s6_hot: false,
  s6_intentHtml: '<b>Visual compression before brand reveal.</b>',
  s6_promptVideo: 'Center-locked shot, elements converge inward.',
  s6_promptStill: 'Symmetrical composition, inward bending trails.',
  s6_negVideo: 'no hard cut into scene',
  s6_negStill: 'no chaotic motion',
  s6_imageMode: 'placeholder',
  s6_imageFile: '',
  s6_phLabel: 'Convergence',
  s6_phHint: 'Vortex / compression ref',
  s6_badge: 'Visual pending',
  s6_brandOutro: false,

  s7_code: 'S7',
  s7_num: '07',
  s7_title: 'Brand outro · Tagline',
  s7_time: '8.8 – 10.0s',
  s7_lens: '85mm · locked off',
  s7_hot: true,
  s7_intentHtml:
    '<b>Fully static frame · text rotation + micro logo glow.</b> Memory imprint for DOOH.',
  s7_promptVideo: 'Cinematic static locked frame, 85mm. Premium DOOH billboard composition.',
  s7_promptStill: 'Static billboard-style composition, logo and tagline.',
  s7_negVideo: 'no characters · no environment · no flashy transitions',
  s7_negStill: 'no gradient pollution',
  s7_imageMode: 'split',
  s7_imageFile: '',
  s7_phLabel: '',
  s7_phHint: '',
  s7_badge: '',
  s7_brandOutro: true,

  /** Public URL path for static stills (not stored inside brief JSON). */
  asset_base_path: '/dooh',
}
